name: flutter_application_1
description: A new Flutter project for Scam Detection Challenge.
publish_to: 'none' # Remove this if you want to publish to pub.dev

version: 1.0.0+9

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1   # for custom fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1   # fixes analysis_options.yaml include error

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets\Delivery\image137.png
    - assets\Delivery\image135.png
    - assets\Delivery\image128.png
    - assets\Delivery\image126.png
    - assets\Delivery\image125.png
    - assets\Delivery\image123.png
    - assets\Delivery\image138.png
    - assets\Delivery\image139.png
    - assets\Delivery\image140.png
    - assets\Delivery\image141.png
    - assets\Delivery\image142.png
    - assets\Delivery\image143.png
    - assets\Delivery\image144.png
    - assets\Delivery\image145.png
    - assets\Delivery\image146.png
    - assets\Delivery\image147.png
    - assets\Delivery\image148.png
    - assets\Delivery\image149.png
    - assets\Delivery\image150.png
    - assets\Delivery\image151.png
    - assets\Delivery\image152.png
    - assets\Delivery\image153.png
    - assets\Delivery\image154.png
    - assets\Delivery\image155.png
    - assets\Delivery\image156.png
    - assets\Delivery\image157.png
    - assets\Delivery\image158.png
    - assets\Delivery\image159.png
    - assets\Delivery\image160.png
    - assets\Delivery\image161.png
    - assets\Delivery\image162.png
    - assets\Delivery\image163.png
    - assets\Delivery\image164.png
    - assets\Jobs\image01.png
    - assets\Jobs\image02.png
    - assets\Jobs\image03.png
    - assets\Jobs\image04.png
    - assets\Jobs\image05.png
    - assets\Jobs\image06.png
    - assets\Jobs\image07.png
    - assets\Jobs\image08.png
    - assets\Jobs\image09.png
    - assets\Jobs\image10.png
    - assets\Jobs\image11.png
    - assets\Jobs\image12.png
    - assets\Jobs\image13.png
    - assets\Jobs\image14.png
    - assets\Jobs\image15.png
    - assets\Jobs\image16.png
    - assets\Jobs\image17.png
    - assets\Jobs\image18.png
    - assets\Jobs\image19.png
    - assets\Jobs\image20.png
    - assets\Jobs\image21.png
    - assets\Jobs\image22.png
    - assets\Jobs\image23.png
    - assets\Jobs\image24.png
    - assets\Jobs\image25.png
    - assets\Jobs\image26.png
    - assets\Jobs\image27.png
    - assets\Jobs\image28.png
    - assets\Seasons\image29.png
    - assets\Seasons\image30.png
    - assets\Seasons\image31.png
    - assets\Seasons\image32.png
    - assets\Seasons\image33.png
    - assets\Seasons\image34.png
    - assets\Seasons\image35.png
    - assets\Seasons\image36.png
    - assets\Seasons\image37.png
    - assets\Seasons\image38.png
    - assets\Seasons\image39.png
    - assets\Seasons\image40.png
    - assets\Seasons\image41.png
    - assets\Seasons\image42.png
    - assets\Seasons\image43.png
    - assets\Seasons\image44.png
    - assets\Seasons\image45.png
    - assets\Seasons\image46.png
    - assets\Seasons\image47.png
    - assets\Seasons\image48.png
    - assets\Seasons\image49.png
    - assets\Seasons\image50.png
    - assets\Seasons\image51.png
    - assets\Seasons\image52.png
    - assets\Seasons\image53.png
    - assets\Seasons\image54.png
    - assets\Seasons\image55.png
    - assets\Seasons\image56.png
    - assets\Seasons\image57.png
    - assets\Seasons\image58.png
    - assets\Seasons\image59.png

